### ISSUE TITLE
didn't seem to get it working

### ISSUE THREAD

**Issue by panlina** [ezartech/ezar-ionic#1]
I followed the steps but all I got is a blank page with title. Is there any necessary steps not mentioned in readme.md?
The problem seems to be that `window.ezar` is `undefined`. I didn't see any script populating it(no things like ezar.js). How does it work?

**Comment by ezartech** [comment]
Fixed. 
Thx for the report. The issue is this ionic bug https://github.com/driftyco/ng-cordova/issues/1028.
Commit: https://github.com/ezartech/ezar-ionic/commit/e84fe3da2346563fc1225c091e7eb8a9d95ad4dd

**Comment by panlina** [comment]
Thanks for the quick fix, but I'm not sure it is the exact issue I'm reporting. The thing is that I find I have to use `cordova.plugins.camerapreview` instead of `CameraPreview` in index.js. I'm using cordova 6.2.0.

**Comment by ezartech** [comment]
Hmmm! camerapreview is not an ezAR plugin.

W

**Comment by panlina** [comment]
Sorry, I'm mistaken. I deleted it already. The latest master branch is working. Thanks!
