### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by shaneparsons** [ezartech/ezar-ionic#3]
It'd be awesome if you could either modify this repo, or create a new one with an Ionic 2 example. Being new to Ionic I'm having a lot of trouble trying to implement this manually.

**Comment by sandrom3w** [comment]
Hi @shaneparsons, I'm having the same trouble as you. Did you find a way to import custom Cordova plugins into Ionic 2?

**Comment by shaneparsons** [comment]
Hey @sandrom3w, he actually created a couple repos for ionic 2 since I opened this:

- https://github.com/ezartech/ezar-ionic2-tabs
- https://github.com/ezartech/ezar-ionic2-sidemenu

To get it working:
- download the plugin from the website and copy it into to the plugins folder.
- add the platforms if needed (i.e. `ionic platform add ios`)
- `cd` into the plugins folder and run `ionic plugin add [path-to-video-overlay]` from there
- add this to the page.ts:
```
var win: any = window;
if (win.ezar) {
  var ezar: any = win.ezar;
  ezar.initializeVideoOverlay(
    function() {
      ezar.getBackCamera().start();
    },
    function(err) {
      alert('unable to init ezar: ' + err);
    });
} else {
  alert('Unable to detect the ezAR plugin');
}
```
- add this to the page.scss:
```
ion-content {
   background-color: transparent;
   color: white !important;
}
```
- and add this to app.scss:
```
//enable ezAR video to show through <body> element
body {
    background-color: transparent;
}

//enable ezAR video to show through ionic app's root component
//hack: prevents theme specific overriding of background-color
ion-app {
    background-color: transparent !important;
}
```
You can compare against the files of one of the repos listed above, but I think I covered everything.

**Comment by shaneparsons** [comment]
As mentioned above there are now 2 repos for Ionic 2, so I'm going to close this issue.
